apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
  - image: skaffold-example
manifests:
  rawYaml:
  - k8s-pod.yaml

customActions:
  - containers: 
      - image: image1
        name: container1
    name: a1
    executionMode:
      kubernetesCluster:
        overrides: "{name: \"renzo\"}"
        jobManifestPath: ./job.yaml